"""add tab switch counters to rooms

Revision ID: 3e695d6cac96
Revises: 4b90960ca9d5
Create Date: 2026-05-30 20:58:56.418482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e695d6cac96'
down_revision: Union[str, None] = '4b90960ca9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('player_a_tab_switches', sa.Integer(), nullable=False,server_default='0'))
    op.add_column('rooms', sa.Column('player_b_tab_switches', sa.Integer(), nullable=False,server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'player_b_tab_switches')
    op.drop_column('rooms', 'player_a_tab_switches')
    # ### end Alembic commands ###
